# Generated by Django 5.2.5 on 2025-08-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.DateField(blank=True, null=True)),
                ('bid_number', models.CharField(blank=True, max_length=100, null=True)),
                ('beneficiary', models.CharField(blank=True, max_length=255, null=True)),
                ('ministry', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('organisation', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_period', models.CharField(blank=True, max_length=255, null=True)),
                ('item_category', models.TextField(blank=True, null=True)),
                ('bid_end_datetime', models.CharField(blank=True, max_length=100, null=True)),
                ('bid_open_datetime', models.CharField(blank=True, max_length=100, null=True)),
                ('bid_offer_validity_days', models.IntegerField(blank=True, null=True)),
                ('similar_category', models.TextField(blank=True, null=True)),
                ('mse_exemption', models.CharField(blank=True, max_length=10, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
