# Generated by Django 5.2.5 on 2025-08-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bids/')),
                ('dated', models.DateField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('bid_number', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('beneficiary', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('office_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ministry', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('organisation', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_bid_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_quantity', models.IntegerField(blank=True, null=True)),
                ('contract_period', models.CharField(blank=True, max_length=255, null=True)),
                ('item_category', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
