# Generated by Django 5.2.5 on 2025-08-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bid_documents/'),
        ),
    ]
