# Generated by Django 5.2.5 on 2025-08-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddocument',
            name='raw_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
