# Generated by Django 5.2.5 on 2025-08-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_record', '0002_biddocument_raw_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddocument',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biddocument',
            name='bid_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
