# Generated by Django 5.2.5 on 2025-08-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_record', '0003_biddocument_embedding_alter_biddocument_bid_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddocument',
            name='bid_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
