# Generated by Django 5.2.5 on 2025-08-11 08:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_no', models.CharField(db_index=True, max_length=64, unique=True)),
                ('generated_date', models.DateField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-generated_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf_files', verbose_name='PDF file')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=128)),
                ('contact_no', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Phone number may contain digits, spaces, +, -, parentheses.', regex='^[\\d\\-\\+\\s\\(\\)]{3,30}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gstin', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='cont_record.contract')),
            ],
        ),
        migrations.CreateModel(
            name='EPBGDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='epbg', to='cont_record.contract')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifd_concurrence', models.BooleanField(default=False)),
                ('admin_approval_designation', models.CharField(blank=True, max_length=256)),
                ('financial_approval_designation', models.CharField(blank=True, max_length=256)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_approval', to='cont_record.contract')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=128)),
                ('ministry', models.CharField(blank=True, max_length=256)),
                ('department', models.CharField(blank=True, max_length=256)),
                ('organisation_name', models.CharField(blank=True, max_length=256)),
                ('office_zone', models.CharField(blank=True, max_length=256)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_details', to='cont_record.contract')),
            ],
        ),
        migrations.CreateModel(
            name='PayingAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=128)),
                ('payment_mode', models.CharField(blank=True, max_length=128)),
                ('designation', models.CharField(blank=True, max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gstin', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paying_authority', to='cont_record.contract')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cont_record.pdffile'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_description', models.TextField(blank=True, verbose_name='Item Description')),
                ('product_name', models.CharField(max_length=512)),
                ('brand', models.CharField(blank=True, max_length=256)),
                ('brand_type', models.CharField(blank=True, max_length=128)),
                ('catalogue_status', models.CharField(blank=True, max_length=256)),
                ('selling_as', models.CharField(blank=True, max_length=256)),
                ('category_name_quadrant', models.CharField(blank=True, max_length=256)),
                ('model', models.CharField(blank=True, max_length=256)),
                ('hsn_code', models.CharField(blank=True, max_length=64)),
                ('ordered_quantity', models.CharField(blank=True, max_length=64, null=True)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('unit_price', models.CharField(blank=True, max_length=64, null=True)),
                ('tax_bifurcation', models.CharField(blank=True, max_length=64, null=True)),
                ('total_price', models.CharField(blank=True, max_length=64, null=True)),
                ('note', models.TextField(blank=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cont_record.contract')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsigneeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Phone number may contain digits, spaces, +, -, parentheses.', regex='^[\\d\\-\\+\\s\\(\\)]{3,30}$')])),
                ('gstin', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('item', models.CharField(blank=True, max_length=256, verbose_name='Item')),
                ('lot_no', models.CharField(blank=True, max_length=128)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('delivery_start', models.DateField(blank=True, null=True)),
                ('delivery_end', models.DateField(blank=True, null=True)),
                ('delivery_to', models.CharField(blank=True, max_length=256)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignees', to='cont_record.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=128)),
                ('sub_spec', models.CharField(blank=True, max_length=256)),
                ('value', models.CharField(blank=True, max_length=512)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='cont_record.product')),
            ],
        ),
        migrations.CreateModel(
            name='SellerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gem_seller_id', models.CharField(blank=True, max_length=64)),
                ('company_name', models.CharField(blank=True, max_length=256)),
                ('contact_no', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Phone number may contain digits, spaces, +, -, parentheses.', regex='^[\\d\\-\\+\\s\\(\\)]{3,30}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('msme_registration_number', models.CharField(blank=True, max_length=64)),
                ('gstin', models.CharField(blank=True, max_length=32)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='cont_record.contract')),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_text', models.TextField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='cont_record.contract')),
            ],
        ),
    ]
