# Generated by Django 5.2.5 on 2025-08-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files', verbose_name='PDF file'),
        ),
    ]
