# Generated by Django 5.2.5 on 2025-08-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consigneedetail',
            name='item',
            field=models.CharField(blank=True, max_length=256, verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_description',
            field=models.TextField(blank=True, verbose_name='Item Description'),
        ),
    ]
