# Generated by Django 5.2.5 on 2025-08-09 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont_record', '0002_contract_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf_files', verbose_name='PDF file')),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='pdf_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cont_record.pdffile'),
        ),
    ]
