# Generated by Django 5.2.5 on 2025-08-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cont_record', '0003_pdffile_alter_contract_pdf_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='pdf_file',
            new_name='file',
        ),
    ]
