# Generated by Django 5.2.5 on 2025-08-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont_record', '0004_rename_pdf_file_contract_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
